<?php

declare(strict_types=1);

namespace EScooters\Utils;

class HardcodedCitiesToCountriesAssigner
{
    public static function assign(string $name): ?string
    {
        return match ($name) {
            "Aalst" => "Belgium",
            "Antwerp" => "Belgium",
            "Aprilia" => "Italy",
            "Bretigny-sur-Orge" => "France",
            "Canterbury" => "United Kingdom",
            "Cascais" => "Portugal",
            "Charleroi" => "Belgium",
            "Erfurt" => "Germany",
            "Espinho" => "Portugal",
            "Évora" => "Portugal",
            "Faro" => "Portugal",
            "Ferrara" => "Italy",
            "Firenze" => "Italy",
            "Liege" => "Belgium",
            "Maia" => "Portugal",
            "Neckarsulm" => "Germany",
            "Neu-Ulm" => "Germany",
            "Orange" => "France",
            "Pesaro" => "Italy",
            "Pforzheim" => "Germany",
            "Porto" => "Portugal",
            "Redditch" => "United Kingdom",
            "Regensburg" => "Germany",
            "Rio de Janeiro" => "Brazil",
            "Tarragona" => "Spain",
            "Tel Aviv" => "Israel",
            "Tomar" => "Portugal",
            "Ulm" => "Germany",
            "Viareggio" => "Italy",
            "Vienna" => "Austria",
            "Vila Franca de Xira" => "Portugal",
            "Vila Nova de Gaia" => "Portugal",
            "Villemomble" => "France",
            "Viry-Chatillon" => "France",
            "Würzburg" => "Germany",
            "Zaragoza" => "Spain",
            "Givatayim" => "Israel",
            "Ramat Gan" => "Israel",
            "Chemnitz" => "Germany",
            "Heilbronn" => "Germany",
            "Kassel" => "Germany",
            "Palermo" => "Italy",
            "Rostock" => "Germany",
            "Troisdorf" => "Germany",
            "Varese" => "Italy",
            "Catania" => "Italy",
            "Monza" => "Italy",
            "Padua" => "Italy",
            "London" => "United Kingdom",
            "Doha" => "Qatar",
            "Cadiz" => "Spain",
            "Castlebar" => "Ireland",
            "Greater Manchester" => "United Kingdom",
            "Sofia" => "Bulgaria",
            "Rybnik" => "Poland",
            "Siedlce" => "Poland",
            "Pruszków" => "Poland",
            "Piaseczno" => "Poland",
            "Leszno" => "Poland",
            "Legionowo" => "Poland",
            "Kielce" => "Poland",
            "Gliwice" => "Poland",
            "Bydgoszcz" => "Poland",
            "Ceske Budejovice" => "Czech Republic",
            "Budapest" => "Hungary",
            "Minsk" => "Belarus",
            "Dresden" => "Germany",
            "Detmold" => "Germany",
            "Dachau" => "Germany",
            "Böblingen" => "Germany",
            "Duisburg" => "Germany",
            "Seoul" => "South Korea",
            "Incheon" => "South Korea",
            "Dubai" => "United Arab Emirates",
            "Râmnicu Vâlcea" => "Romania",
            "Brasov" => "Romania",
            "Alba Iulia" => "Romania",
            "Arad" => "Romania",
            "Daejeon" => "South Korea",
            "Busan" => "South Korea",

            default => null,
        };
    }
}
